# See https://pre-commit.com/ for usage and config
repos:
- repo: local
  hooks:
  - id: task-test
    name: Task Test
    stages: [commit]
    language: system
    entry: task test
    pass_filenames: false
    verbose: true
